const ACTION_TYPES = {
    GET_PRODUCTS_LIST: "GET_PRODUCTS_LIST",
    GET_PRODUCT: "GET_PRODUCT",
    ADD_PRODUCT_IN_CART: "ADD_PRODUCT_IN_CART",
    REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
    TOGGLE_LOADING: "TOGGLE_LOADING"  
}; 

export default ACTION_TYPES;